### ISSUE TITLE
Salt needs to be generated - IMPORTANT

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/Security_and_FullstackJavascript_Exam#30]
In the userFacade where we add a user we need to generate the salt - rigth now it's just hardcoded as 10:
![image](https://user-images.githubusercontent.com/35559774/82830706-c1bf5600-9eb6-11ea-9b89-45e9fe70d44d.png)

Should look lige this:
![image](https://user-images.githubusercontent.com/35559774/82830756-dd2a6100-9eb6-11ea-9114-e05bfdb3fce5.png)

It's fine that the saltrounds are hardcoded as 10, but we need to generate the salt itself. 

This needs to be fixed before security report is due.

**Comment by Runi-VN** [comment]
I think the function does what we intend it to do, already? Or maybe I am missing something. 

From the bottom of [this](https://www.npmjs.com/package/bcryptjs#usage---async) paragraph:
![image](https://user-images.githubusercontent.com/37186286/82838420-6ef09900-9ecc-11ea-902e-41f1dca414b7.png)
where `bacon` is the string and `8` is the salt rounds.

**Comment by Castau** [comment]
> I think the function does what we intend it to do, already? Or maybe I am missing something.

That's a good find - i checked the database and it looks like it's working as intended.
![image](https://user-images.githubusercontent.com/35559774/82869535-b9a2fd00-9f2e-11ea-9f6c-b70230f7c949.png)

Then there's no issue :D
