### ISSUE TITLE
NO TOKEN spam

### ISSUE THREAD

**Issue by MrHardcode** [Hold-Krykke/Security_and_FullstackJavascript_Exam#38]
![image](https://user-images.githubusercontent.com/44898491/83192378-ba59b000-a135-11ea-9d35-7184bdca87d1.png)
I don't know what's printing this so aggressively but we need to figure out why this is being printed a million times and make it stop

**Comment by MrHardcode** [comment]
> Den console.log er i server.ts der hvor den oprettet Apollo server under context under den case hvor req.headers.authorization er tom

**Comment by MalteMagnussen** [comment]
GraphQL playground is polling the backend for updates.

**Comment by MalteMagnussen** [comment]
https://stackoverflow.com/questions/57531999/continous-console-log-in-express-graphql-app

**Comment by MalteMagnussen** [comment]
![image](https://user-images.githubusercontent.com/11192971/83271389-179f4100-a1ca-11ea-962a-dd2ac56ee793.png)
![image](https://raw.githubusercontent.com/aspnetzero/documents/master/docs/en/images/graphql_playground_settings.jpg)

**Comment by MalteMagnussen** [comment]
https://medium.com/novvum/graphql-playground-v1-8-8-introducing-automatic-schema-reload-6c9da4bbd552

**Comment by MalteMagnussen** [comment]
Jeg tror ikke det er et problem med backend, men en "polling" feature during development

**Comment by HrBjarup** [comment]
Oh okay have you tested it?
