### ISSUE TITLE
Security/Rapport

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/Security_and_FullstackJavascript_Exam#5]
I forhold til rapporten skal følgende være opfyldt:
* 10-15 “siders” rapport pr. Fag i hver sin readme-format (ala artikelformat)
* Beskriv/argumenter for fordele/ulemper ved mongoDB iforhold til mySQL database
* Problemer ved mongoDB ift injections?  
  
**GENERELT**  
* Nedskriv alle overvejelser undervejs
* Ved opsætning af droplets, gør nogle overvejelser i forhold til de ting vi har lært i security

**Comment by MalteMagnussen** [comment]
> 10-15 “siders” rapport pr. Fag

Skal der både være en JavaScript og Security Rapport på 10-15 sider hver, da? Var det ikke kun 1 Security rapport?

**Comment by MrHardcode** [comment]
Mener vi til at begynde med forstod som at vi skulle have en rapport for hvert fag, men at Lars sagde, vi ikke behøvede en i FSJS. Han sagde jo også det der med, at vi i princippet måtte arbejde på projektet helt indtil eksamen i FSJS
