### ISSUE TITLE
We should reset cache on logout

### ISSUE THREAD

**Issue by MalteMagnussen** [Hold-Krykke/Security_and_FullstackJavascript_Exam#60]
https://www.apollographql.com/docs/react/networking/authentication/#reset-store-on-logout

**Comment by MrHardcode** [comment]
```ts
import * as SecureStore from "expo-secure-store";
const secureStoreKey = "token";

// Inside the App() function:
const logout = async () => {
    Promise.all([client.clearStore(), SecureStore.deleteItemAsync(secureStoreKey),
    ]).then(() => {
      console.log("User has logged out");
      setSignedIn(false); 
    });
 };
```
Place this code in `App.js` and pass the function to the components that have logout-functionality.

`secureStoreKey` should be placed in the `settings.js` so it is consistent across components.
